version: '3'
services:
  scapy:
    build: .
    image: scapy:v1.6
    container_name: ppx_mall_scrapy
    environment:
        - TZ=Asia/Shanghai
    restart: "no"
    volumes:
      - .:/app
      - /data/www/mall.jimiws.com/data/upload/shop/store/goods/1:/app/au51gogoods/au51gogoods/image/1
      - /data/www/mall.jimiws.com/data/upload/shop/store/goods/4:/app/au51gogoods/au51gogoods/image/4
      - /data/www/mall.jimiws.com/data/upload/shop/store/goods/1:/app/soukuangoods/soukuangoods/image/1
      - /data/www/mall.jimiws.com/data/upload/shop/store/goods/1:/app/shenrong/image/1
      - /data/www/mall.jimiws.com/data/upload/shop/store/goods/1:/app/Fix/Fix/image/1
      - /data/www/mall.jimiws.com/data/upload/shop/store/goods/6:/app/lotte/image/6